# Generated by Django 5.0.1 on 2026-02-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0001_initial"),
        ("category", "0002_auto_20201006_0125"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="category.category",
            ),
        ),
    ]
