# Generated by Django 5.0.1 on 2026-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20210321_0717"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
